from __future__ import annotations


class CustomError(Exception): ...
